/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    
    maven {
        url = uri("https://litarvan.github.io/maven")
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    
    // To update minecraft version
    implementation("fr.flowarg:openlauncherlib:3.2.11")
    // To launch the game
    implementation("fr.flowarg:flowupdater:1.9.4")
    // For authentification
    implementation("fr.litarvan:openauth:1.1.6")
    // For json
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "21.0.2"
    modules = listOf("javafx.controls")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

application {
    mainClass.set("launcher.Main")
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "launcher.Main"
    }
}
